# Generated by Django 2.0.4 on 2018-05-03 17:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer', models.IntegerField()),
                ('datetimenew', models.DateField(default=django.utils.timezone.now)),
                ('char', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='referrer',
            name='foreign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreign_test', to='foreign_fields.Target'),
        ),
        migrations.AddField(
            model_name='referrer',
            name='many',
            field=models.ManyToManyField(blank=True, related_name='many_test', to='foreign_fields.Target'),
        ),
    ]
